def escovar_dentes():
    from voz import maquina_voz
    from time import sleep
    maquina_voz("ESTA NA HORA DE ESCOVARMOS OS DENTES!")
    sleep(1)
    maquina_voz("VOU TE ENSINAR O PASSO A PASSO PARA VOCÊ APRENDER UMA BOA ESCOVAÇÃO,E FICAR LIVRE DE CÁRIES!")
    sleep(1)
    maquina_voz('VAMOS COMEÇAR')
    sleep(1)
    maquina_voz("O PRIMEIRO PASSO É COLOCAR UM POUQUINHO DE PASTA DE DENTES NA ESCOVA")
    sleep(0.5)
    maquina_voz('PEGUE A PASTA DE DENTE E APERTE SUAVEMENTE SOBRE A ESCOVA, ATÉ SAIR UM PINGUINHO DE PASTA')
    sleep(3)
    maquina_voz("O SEGUNDO PASSO É, COMEÇAR LIMPANDO OS DENTES DO FUNDO DA BOCA DA PARTE DE FORA!")
    sleep(0.3)
    maquina_voz("LIMPE EM CIMA E EM BAIXO, COM MOVIMENTOS CIRCULARES, POR 5 SEGUNDOS")
    sleep(0.5)
    maquina_voz('VAMOS LÁ, COMECE A ESCOVAR QUANDO COMEÇAR A CONTAGEM..')
    sleep(0.5)
    maquina_voz('1')
    sleep(1)
    maquina_voz('2')
    sleep(1)
    maquina_voz('3')
    sleep(1)
    maquina_voz('4')
    sleep(1)
    maquina_voz('5')
    sleep(0.5)
    maquina_voz("AGORA NO TERCEIRO PASSO, LIMPE A PARTE DE DENTRO DOS DENTES DE CIMA PRA BAIXO!")
    sleep(0.3)
    maquina_voz('LIMPANDO BEM OS DENTES DO FUNDO, POR 5 SEGUNDOS')
    sleep(0.5)
    maquina_voz('COMECE A ESCOVAR QUANDO COMEÇAR A CONTAGEM..')
    sleep(0.5)
    maquina_voz('1')
    sleep(1)
    maquina_voz('2')
    sleep(1)
    maquina_voz('3')
    sleep(1)
    maquina_voz('4')
    sleep(1)
    maquina_voz('5')
    sleep(0.5)
    maquina_voz("O QUARTO PASSO, COMEÇA COM A ESCOVAÇÃO NA BORDA DOS DENTES MOVIMENTANDO PARA FRENTE E PARA TRÁS, POR 5 SEGUNDOS")
    sleep(0.5)
    maquina_voz('VAMOS LÁ, COMECE QUANDO COMEÇAR A CONTAGEM..')
    sleep(1)
    maquina_voz('1')
    sleep(1)
    maquina_voz('2')
    sleep(1)
    maquina_voz('3')
    sleep(1)
    maquina_voz('4')
    sleep(1)
    maquina_voz('5')
    sleep(0.5)
    maquina_voz("NO QUINTO PASSO, VAMOS AGORA LIMPAR O RESTO DA BOCA!")
    sleep(0.3)
    maquina_voz("PASSE A ESCOVA SUAVEMENTE PELO INTERIOR DE SUAS BUCHECHAS E PELA LÍNGUA, POR 5 SEGUNDOS")
    sleep(0.5)
    maquina_voz('VAMOS LÁ, COMECE A ESCOVAÇÃO QUANDO COMEÇAR A CONTAGEM..')
    sleep(0.5)
    maquina_voz('1')
    sleep(1)
    maquina_voz('2')
    sleep(1)
    maquina_voz('3')
    sleep(1)
    maquina_voz('4')
    sleep(1)
    maquina_voz('5')
    sleep(0.5)
    maquina_voz("E POR ULTIMO NO SEXTO PASSO, VAMOS CUSPIR NA PIA A ESPUMA QUE SE ACUMULOU!")
    sleep(2)
    maquina_voz("AGORA ENCHA A BOCA COM ÁGUA FAZENDO UMA LAVAGEM GERAL E ENXAGUE!")
    sleep(2)
    maquina_voz("AGORA CUSPA O LIQUIDO DA BOCA")
    sleep(1)
    maquina_voz('PARABENS!! VOCÊ APENDEU COMO SE ESCOVAR OS DENTES!!')
    sleep(0.5)
    maquina_voz('CONTE COMIGO SEMPRE QUE PRECISAR!')
